INSERT INTO COURSE(ID, AUTHOR, NAME) VALUES(10001, 'VIBHAM', 'MICROSERVICES');
INSERT INTO COURSE(ID, AUTHOR, NAME) VALUES(10002, 'SHAILY', 'REACT JS');
INSERT INTO COURSE(ID, AUTHOR, NAME) VALUES(10003, 'VIBHAM SHARMA', 'SPRING FRAMEWORK');
INSERT INTO COURSE(ID, AUTHOR, NAME) VALUES(10004, 'SHAILY SHARMA', 'REACT NATIVE');